<script lang="ts">
  import InlineProgress from '$lib/components/dashboard/InlineProgress.svelte';
  import QualityStatusBadge from '$lib/components/dashboard/QualityStatusBadge.svelte';
  import type { SquadQualityProject } from '$lib/api/statistics';
  import type { ProjectHealthStatus } from '$lib/api/projects';
  import { formatPercent } from '$lib/utils/format';
  let { projects }: { projects: SquadQualityProject[] } = $props();
  let search = $state(''); let status = $state<ProjectHealthStatus | ''>(''); let sort = $state<'coverage' | 'passRate' | 'activity'>('coverage');
  const rows = $derived.by(() => projects.filter((project) => (!search || project.name.toLowerCase().includes(search.toLowerCase()) || project.key.toLowerCase().includes(search.toLowerCase())) && (!status || project.status === status)).toSorted((a, b) => { if (sort === 'activity') return (b.lastExecutionAt ?? '').localeCompare(a.lastExecutionAt ?? ''); const av = sort === 'coverage' ? a.coveragePercent : a.passRatePercent; const bv = sort === 'coverage' ? b.coveragePercent : b.passRatePercent; return (av ?? -1) - (bv ?? -1); }));
  function activity(value: string | null) { if (!value) return 'Never'; const days = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 86_400_000)); return days === 0 ? 'Today' : `${days}d ago`; }
</script>

<section><div class="heading"><h2>Project quality</h2><div class="controls"><input aria-label="Search projects" placeholder="Search projects" bind:value={search} /><select aria-label="Filter by status" bind:value={status}><option value="">All statuses</option><option value="HEALTHY">Healthy</option><option value="NEEDS_REVIEW">Needs review</option><option value="HIGH_RISK">High risk</option><option value="CRITICAL">Critical</option><option value="NO_RUNS">No runs</option></select><select aria-label="Sort projects" bind:value={sort}><option value="coverage">Coverage</option><option value="passRate">Pass rate</option><option value="activity">Last activity</option></select></div></div><div class="table-shell"><table><thead><tr><th>Project</th><th>Scenarios</th><th>Automated</th><th>Coverage</th><th>Pass rate</th><th>Failures</th><th>Status</th><th>Last activity</th></tr></thead><tbody>{#each rows as project (project.id)}<tr><td><a href={`/projects/${project.key}`}><strong>{project.name}</strong><span>{project.key}</span></a></td><td>{project.totalScenarios}</td><td>{project.automatedScenarios}</td><td>{project.coveragePercent == null ? 'N/A' : ''}{#if project.coveragePercent != null}<InlineProgress value={project.coveragePercent} label={`${project.name} coverage`} />{/if}</td><td>{project.passRatePercent == null ? 'No runs' : ''}{#if project.passRatePercent != null}<InlineProgress value={project.passRatePercent} label={`${project.name} pass rate`} />{/if}</td><td>{project.openFailures ?? 'N/A'}</td><td><QualityStatusBadge status={project.status} /></td><td title={project.lastExecutionAt ? new Date(project.lastExecutionAt).toLocaleString() : 'No execution data'}>{activity(project.lastExecutionAt)}</td></tr>{:else}<tr><td colspan="8" class="empty">No matching projects.</td></tr>{/each}</tbody></table></div></section>

<style>
  .heading, .controls { display: flex; align-items: center; justify-content: space-between; gap: 0.6rem; flex-wrap: wrap; } h2 { margin: 0; color: var(--color-text); font-size: 1rem; }
  input, select { min-height: 2.2rem; border: 1px solid var(--color-border); border-radius: 0.45rem; background: var(--color-bg); color: var(--color-text); padding: 0 0.55rem; font: inherit; font-size: 0.75rem; }
  .table-shell { margin-top: 0.75rem; overflow-x: auto; border: 1px solid var(--color-border); border-radius: 0.75rem; } table { width: 100%; min-width: 980px; border-collapse: collapse; background: var(--color-surface); } th, td { padding: 0.75rem; border-bottom: 1px solid var(--color-border); text-align: left; font-size: 0.76rem; } th { color: var(--color-text-muted); font-size: 0.66rem; text-transform: uppercase; } tr:last-child td { border-bottom: 0; } td a { display: grid; color: var(--color-accent); text-decoration: none; } td a span { color: var(--color-text-muted); font-size: 0.66rem; } .empty { color: var(--color-text-muted); text-align: center; }
</style>
